### PR TITLE
Cd fix broken build

### PR DESCRIPTION
**Pull request by georgportwich**

### CODE REVIEW

**Comment by kpanier** [comment]
The renaming and teamservice check is clear.

I tried a clean install build with integrationtests. They failed in the svn .test bundle at test: testReleaseLockedSVNDir

With that failure we can't merge
:-1:

**Comment by georgportwich** [comment]
It is working on my machine. When will we have CI builds running for feature branches to check the build?

**Comment by franzbecker** [comment]
The branch does not comply with the naming convention. We will only generate jobs for branches that start with `feature/`. We could think about changing that if that is wanted.

**Comment by kpanier** [comment]
I checked in a fix for the tet failure on linux systems.

It was my advice to start the prefix with cd/, because it is not a feature.

**Pull request merged**
